# Generated by Django 2.2.7 on 2020-03-15 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Family Chatroom', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ChoreList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Claim_Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('member', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EventEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('start_time', models.CharField(max_length=50)),
                ('duration', models.PositiveIntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='MealDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default=None, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfBirth', models.DateField()),
                ('userType', models.CharField(choices=[('FamilyMember', 'Regular Family Member'), ('Guardian', 'Guardian')], max_length=50)),
                ('genderType', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Prefer not to say')], max_length=50, null=True)),
                ('profilePic', models.ImageField(default='static/empty-photo.jpg', upload_to='static/')),
                ('points', models.PositiveIntegerField(default='0')),
                ('Currentpoints', models.PositiveIntegerField(default='0')),
                ('long', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('timeOfLocation', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pointsNeeded', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('chore', models.BooleanField(default=False)),
                ('assignTaskTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_task_to', to='mainapp.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('timePublished', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author', to='mainapp.Member')),
            ],
        ),
        migrations.CreateModel(
            name='MealWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friB', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friB', to='mainapp.MealDesc')),
                ('friD', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friD', to='mainapp.MealDesc')),
                ('friL', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friL', to='mainapp.MealDesc')),
                ('monB', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monb', to='mainapp.MealDesc')),
                ('monD', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monD', to='mainapp.MealDesc')),
                ('monL', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monL', to='mainapp.MealDesc')),
                ('satB', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satB', to='mainapp.MealDesc')),
                ('satD', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satD', to='mainapp.MealDesc')),
                ('satL', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satL', to='mainapp.MealDesc')),
                ('sunB', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunB', to='mainapp.MealDesc')),
                ('sunD', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunD', to='mainapp.MealDesc')),
                ('sunL', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunL', to='mainapp.MealDesc')),
                ('thuB', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thuB', to='mainapp.MealDesc')),
                ('thuD', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thuD', to='mainapp.MealDesc')),
                ('thuL', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thuL', to='mainapp.MealDesc')),
                ('tueB', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tueB', to='mainapp.MealDesc')),
                ('tueD', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tueD', to='mainapp.MealDesc')),
                ('tueL', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tueL', to='mainapp.MealDesc')),
                ('wedB', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wedB', to='mainapp.MealDesc')),
                ('wedD', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wedD', to='mainapp.MealDesc')),
                ('wedL', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wedL', to='mainapp.MealDesc')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfList', models.CharField(max_length=30)),
                ('task', models.ManyToManyField(blank=True, to='mainapp.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofFamily', models.CharField(max_length=30)),
                ('FamKey', models.CharField(default=mainapp.models.create_new_ref_number, max_length=30, unique=True)),
                ('cal', models.BooleanField(default=False)),
                ('calId', models.CharField(blank=True, max_length=60, null=True)),
                ('calEvents', models.ManyToManyField(blank=True, to='mainapp.EventEntry')),
                ('chatroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Chatroom')),
                ('choreList', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ChoreList')),
                ('lists', models.ManyToManyField(blank=True, to='mainapp.List')),
                ('mealPlan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.MealWeek')),
                ('members', models.ManyToManyField(to='mainapp.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Chores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('points', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('dueBy', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('assignChoreTo', models.ManyToManyField(blank=True, to='mainapp.Member')),
            ],
        ),
        migrations.AddField(
            model_name='chorelist',
            name='chores',
            field=models.ManyToManyField(blank=True, to='mainapp.Chores'),
        ),
        migrations.AddField(
            model_name='chorelist',
            name='claim',
            field=models.ManyToManyField(blank=True, to='mainapp.Claim_Reward'),
        ),
        migrations.AddField(
            model_name='chorelist',
            name='rewards',
            field=models.ManyToManyField(blank=True, to='mainapp.Rewards'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='messages',
            field=models.ManyToManyField(blank=True, to='mainapp.Message'),
        ),
    ]
