# Generated by Django 3.0 on 2019-12-15 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evententry',
            old_name='title',
            new_name='name',
        ),
    ]
