# Generated by Django 2.2.7 on 2020-03-15 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chorelist',
            name='claim',
        ),
        migrations.DeleteModel(
            name='Claim_Reward',
        ),
    ]
