# Generated by Django 2.2.7 on 2019-11-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20191128_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('reward', models.CharField(max_length=30)),
                ('dueBy', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='family',
            name='list',
        ),
        migrations.AddField(
            model_name='family',
            name='lists',
            field=models.ManyToManyField(to='mainapp.List'),
        ),
        migrations.AddField(
            model_name='list',
            name='nameOfList',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
