# Generated by Django 2.2.7 on 2019-11-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20191128_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='lists',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.List'),
        ),
    ]
