# Generated by Django 2.2.7 on 2020-03-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200316_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimreward',
            name='member',
            field=models.CharField(max_length=30),
        ),
    ]
