# Generated by Django 2.2.7 on 2020-01-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20191215_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thur', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=50)),
                ('MealType', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='evententry',
            name='time',
        ),
        migrations.AddField(
            model_name='evententry',
            name='start_time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
