# Generated by Django 2.2.7 on 2020-05-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200316_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='profilePic',
        ),
    ]
