# Generated by Django 3.0 on 2019-12-08 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20191128_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignTo',
        ),
        migrations.AddField(
            model_name='chores',
            name='assignChoreTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_chore_to', to='mainapp.Member'),
        ),
        migrations.AddField(
            model_name='chores',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chores',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='assignTaskTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_task_to', to='mainapp.Member'),
        ),
    ]
