# Generated by Django 2.2.7 on 2020-01-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200130_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='Day',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='MealType',
            new_name='mealType',
        ),
        migrations.AddField(
            model_name='meal',
            name='description',
            field=models.TextField(default='Dinner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='meal',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
