# Generated by Django 3.0 on 2019-12-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20191208_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='task',
            field=models.ManyToManyField(null=True, to='mainapp.Task'),
        ),
    ]
