# Generated by Django 3.0 on 2019-12-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20191208_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='task',
            field=models.ManyToManyField(blank=True, to='mainapp.Task'),
        ),
    ]
