# Generated by Django 2.2.7 on 2020-01-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20200130_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealtype',
            name='mealType',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=50),
        ),
    ]
