# Generated by Django 3.0 on 2020-02-02 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20200130_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friB', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friB', to='mainapp.MealDesc')),
                ('friD', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friD', to='mainapp.MealDesc')),
                ('friL', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friL', to='mainapp.MealDesc')),
                ('monB', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monb', to='mainapp.MealDesc')),
                ('monD', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monD', to='mainapp.MealDesc')),
                ('monL', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monL', to='mainapp.MealDesc')),
                ('satB', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='satB', to='mainapp.MealDesc')),
                ('satD', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='satD', to='mainapp.MealDesc')),
                ('satL', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='satL', to='mainapp.MealDesc')),
                ('sunB', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sunB', to='mainapp.MealDesc')),
                ('sunD', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sunD', to='mainapp.MealDesc')),
                ('sunL', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sunL', to='mainapp.MealDesc')),
                ('thuB', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thuB', to='mainapp.MealDesc')),
                ('thuD', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thuD', to='mainapp.MealDesc')),
                ('thuL', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thuL', to='mainapp.MealDesc')),
                ('tueB', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tueB', to='mainapp.MealDesc')),
                ('tueD', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tueD', to='mainapp.MealDesc')),
                ('tueL', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tueL', to='mainapp.MealDesc')),
                ('wedB', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wedB', to='mainapp.MealDesc')),
                ('wedD', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wedD', to='mainapp.MealDesc')),
                ('wedL', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wedL', to='mainapp.MealDesc')),
            ],
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.AddField(
            model_name='family',
            name='mealPlan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.MealWeek'),
        ),
    ]
