# Generated by Django 3.0 on 2020-02-02 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20200202_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealweek',
            name='friB',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friB', to='mainapp.MealDesc'),
        ),
        migrations.AlterField(
            model_name='mealweek',
            name='friD',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friD', to='mainapp.MealDesc'),
        ),
        migrations.AlterField(
            model_name='mealweek',
            name='friL',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friL', to='mainapp.MealDesc'),
        ),
        migrations.AlterField(
            model_name='mealweek',
            name='monB',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monb', to='mainapp.MealDesc'),
        ),
        migrations.AlterField(
            model_name='mealweek',
            name='monD',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monD', to='mainapp.MealDesc'),
        ),
        migrations.AlterField(
            model_name='mealweek',
            name='monL',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monL', to='mainapp.MealDesc'),
        ),
        migrations.AlterField(
            model_name='mealweek',
            name='satB',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='satB', to='mainapp.MealDesc'),
        ),
        migrations.AlterField(
            model_name='mealweek',
            name='satD',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='satD', to='mainapp.MealDesc'),
        ),
        migrations.AlterField(
            model_name='mealweek',
            name='satL',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='satL', to='mainapp.MealDesc'),
        ),
        migrations.AlterField(
            model_name='mealweek',
            name='sunB',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sunB', to='mainapp.MealDesc'),
        ),
        migrations.AlterField(
            model_name='mealweek',
            name='sunD',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sunD', to='mainapp.MealDesc'),
        ),
        migrations.AlterField(
            model_name='mealweek',
            name='sunL',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sunL', to='mainapp.MealDesc'),
        ),
        migrations.AlterField(
            model_name='mealweek',
            name='thuB',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thuB', to='mainapp.MealDesc'),
        ),
        migrations.AlterField(
            model_name='mealweek',
            name='thuD',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thuD', to='mainapp.MealDesc'),
        ),
        migrations.AlterField(
            model_name='mealweek',
            name='thuL',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thuL', to='mainapp.MealDesc'),
        ),
        migrations.AlterField(
            model_name='mealweek',
            name='tueB',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tueB', to='mainapp.MealDesc'),
        ),
        migrations.AlterField(
            model_name='mealweek',
            name='tueD',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tueD', to='mainapp.MealDesc'),
        ),
        migrations.AlterField(
            model_name='mealweek',
            name='tueL',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tueL', to='mainapp.MealDesc'),
        ),
        migrations.AlterField(
            model_name='mealweek',
            name='wedB',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wedB', to='mainapp.MealDesc'),
        ),
        migrations.AlterField(
            model_name='mealweek',
            name='wedD',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wedD', to='mainapp.MealDesc'),
        ),
        migrations.AlterField(
            model_name='mealweek',
            name='wedL',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wedL', to='mainapp.MealDesc'),
        ),
    ]
