# Generated by Django 3.0 on 2020-02-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_auto_20200202_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealdesc',
            name='text',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
