# Generated by Django 3.0 on 2020-02-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_auto_20200202_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profilePic',
            field=models.ImageField(default='/static/empty-photo.jpg', upload_to='static/'),
        ),
    ]
