# Generated by Django 2.2.7 on 2020-02-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_auto_20200202_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='FamKey',
            field=models.CharField(blank=True, default='NPnETKtjMjkN', max_length=30),
        ),
    ]
