# Generated by Django 2.2.7 on 2020-02-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_family_famkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='FamKey',
            field=models.CharField(default='e4bYf89838LL', max_length=30, unique=True),
        ),
    ]
