# Generated by Django 2.2.7 on 2020-02-05 21:22

from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_auto_20200204_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='FamKey',
            field=models.CharField(default=mainapp.models.create_new_ref_number, max_length=30, unique=True),
        ),
        migrations.RemoveField(
            model_name='family',
            name='lists',
        ),
        migrations.AddField(
            model_name='family',
            name='lists',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='mainapp.List'),
            preserve_default=False,
        ),
    ]
