# Generated by Django 2.2.7 on 2020-02-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_auto_20200205_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='lists',
        ),
        migrations.AddField(
            model_name='family',
            name='lists',
            field=models.ManyToManyField(blank=True, to='mainapp.List'),
        ),
    ]
