# Generated by Django 2.2.7 on 2020-02-09 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_auto_20200205_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=30)),
                ('timePublished', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='static/')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='mainapp.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='mainapp.Message')),
            ],
        ),
    ]
