# Generated by Django 2.2.7 on 2020-02-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_chatroom_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='name',
            field=models.CharField(default='hey', max_length=30),
            preserve_default=False,
        ),
    ]
