# Generated by Django 2.2.7 on 2020-02-09 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_auto_20200209_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='chatroom',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Chatroom'),
        ),
        migrations.AlterField(
            model_name='family',
            name='mealPlan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.MealWeek'),
        ),
    ]
