# Generated by Django 2.2.7 on 2020-02-09 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_auto_20200209_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(default='Family Chatroom', max_length=30),
        ),
        migrations.AlterField(
            model_name='family',
            name='chatroom',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Chatroom'),
        ),
    ]
