# Generated by Django 2.2.7 on 2020-02-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_auto_20200210_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profilePic',
            field=models.ImageField(default='mainapp/static/empty-photo.jpg', upload_to='mainapp/static/mainapp'),
        ),
        migrations.AlterField(
            model_name='member',
            name='userType',
            field=models.CharField(choices=[('FamilyMember', 'Regular Family Member'), ('Guardian', 'Guardian')], max_length=50),
        ),
    ]
