# Generated by Django 2.2.7 on 2020-02-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_auto_20200211_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profilePic',
            field=models.ImageField(default='static/empty-photo.jpg', upload_to='static/'),
        ),
    ]
