# Generated by Django 2.2.7 on 2020-02-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0041_auto_20200211_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='genderType',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Prefer not to say')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='points',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
