# Generated by Django 2.2.7 on 2020-02-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0042_auto_20200213_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='tasksCompleted',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
