# Generated by Django 2.2.7 on 2020-02-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0043_member_taskscompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='auth',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
