# Generated by Django 2.2.7 on 2020-02-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0044_member_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='chore',
            field=models.BooleanField(default=False),
        ),
    ]
