# Generated by Django 2.2.7 on 2020-02-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0045_task_chore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='profilePic',
        ),
    ]
