# Generated by Django 2.2.7 on 2020-02-19 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0047_auto_20200219_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='currentLocation',
        ),
        migrations.RemoveField(
            model_name='member',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='member',
            name='long',
        ),
    ]
