# Generated by Django 2.2.7 on 2020-02-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0048_auto_20200219_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='currentLocation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='timeOfLocation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
