# Generated by Django 2.2.7 on 2020-02-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0049_auto_20200219_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profilePic',
            field=models.ImageField(default='static/empty-photo.jpg', upload_to='static/'),
        ),
    ]
