# Generated by Django 2.2.7 on 2020-02-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0050_member_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='timeOfLocation',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
