# Generated by Django 2.2.7 on 2020-02-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0051_auto_20200219_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='timeOfLocation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
