# Generated by Django 2.2.7 on 2020-02-22 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0052_auto_20200219_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='auth',
            new_name='credentials',
        ),
        migrations.RemoveField(
            model_name='member',
            name='currentLocation',
        ),
    ]
