# Generated by Django 2.2.7 on 2020-02-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0053_auto_20200222_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='credentials',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
