# Generated by Django 2.2.7 on 2020-02-22 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0054_auto_20200222_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='credentials',
        ),
    ]
