# Generated by Django 2.2.7 on 2020-02-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0055_remove_member_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='credentials',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
