# Generated by Django 2.2.7 on 2020-02-22 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0056_member_credentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='credentials',
        ),
    ]
