# Generated by Django 2.2.7 on 2020-02-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0057_remove_member_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='cal',
            field=models.BooleanField(default=False),
        ),
    ]
