# Generated by Django 2.2.7 on 2020-02-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0058_family_cal'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='calId',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
