# Generated by Django 2.2.7 on 2020-02-23 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0060_auto_20200223_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evententry',
            old_name='title',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='evententry',
            name='date',
        ),
        migrations.RemoveField(
            model_name='evententry',
            name='membersInvolved',
        ),
        migrations.AddField(
            model_name='evententry',
            name='attendees',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='evententry',
            name='duration',
            field=models.PositiveIntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='evententry',
            name='family',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='mainapp.Family'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evententry',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='evententry',
            name='start_time',
            field=models.CharField(max_length=50),
        ),
    ]
