# Generated by Django 2.2.7 on 2020-02-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0061_auto_20200223_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evententry',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
