# Generated by Django 2.2.7 on 2020-02-23 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0062_auto_20200223_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evententry',
            name='attendees',
        ),
    ]
