# Generated by Django 2.2.7 on 2020-02-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0063_remove_evententry_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evententry',
            name='family',
        ),
        migrations.AddField(
            model_name='family',
            name='calEvents',
            field=models.ManyToManyField(blank=True, to='mainapp.EventEntry'),
        ),
    ]
