# Generated by Django 2.2.7 on 2020-03-05 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0065_auto_20200305_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='choreList',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ChoreList'),
        ),
    ]
