# Generated by Django 2.2.7 on 2020-03-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0066_auto_20200305_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chores',
            name='reward',
        ),
        migrations.RemoveField(
            model_name='rewards',
            name='points',
        ),
        migrations.AddField(
            model_name='chores',
            name='points',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rewards',
            name='pointsNeeded',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
