# Generated by Django 2.2.7 on 2020-03-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0067_auto_20200305_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chores',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chores',
            name='dueBy',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
